#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Infinite Idol Marketing Team Infrastructure
# This is a documentation repository - no runtime services required

set -e

echo "========================================"
echo "Infinite Idol Marketing HQ Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFICATION ONLY
# This is a documentation repository
# No services to start
# ============================================

echo ""
echo -e "${YELLOW}Note: This is a documentation repository${NC}"
echo "No runtime services to start."
echo ""

# Verify source files exist
echo "Checking source files..."
if [ -f "FULL_AUTO_CLAUDE_PROMPT.md" ]; then
    echo -e "${GREEN}✓ FULL_AUTO_CLAUDE_PROMPT.md exists${NC}"
else
    echo -e "${RED}✗ FULL_AUTO_CLAUDE_PROMPT.md missing${NC}"
    exit 1
fi

if [ -f "SOURCE_MATERIALS_APPENDIX.md" ]; then
    echo -e "${GREEN}✓ SOURCE_MATERIALS_APPENDIX.md exists${NC}"
else
    echo -e "${RED}✗ SOURCE_MATERIALS_APPENDIX.md missing${NC}"
    exit 1
fi

# Check if structure already exists
echo ""
echo "Checking existing structure..."
MD_COUNT=$(find . -name "*.md" -not -path "./.auto-claude/*" 2>/dev/null | wc -l | tr -d ' ')
DIR_COUNT=$(find . -type d -not -path "./.auto-claude*" -not -path "./.git*" 2>/dev/null | wc -l | tr -d ' ')

echo "Current state:"
echo "  - Markdown files: $MD_COUNT"
echo "  - Directories: $DIR_COUNT"

if [ "$MD_COUNT" -ge 45 ] && [ "$DIR_COUNT" -ge 25 ]; then
    echo ""
    echo -e "${GREEN}✓ Repository structure appears complete!${NC}"
else
    echo ""
    echo -e "${YELLOW}Repository structure incomplete - implementation needed${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Check Complete"
echo "========================================"
echo ""
echo "Source Files:"
echo "  - FULL_AUTO_CLAUDE_PROMPT.md (main instructions)"
echo "  - SOURCE_MATERIALS_APPENDIX.md (lore + mechanics content)"
echo ""
echo "To run the implementation:"
echo "  source auto-claude/.venv/bin/activate && python auto-claude/run.py --spec 001 --parallel 2"
echo ""
echo "Success criteria (45+ markdown files, 25+ directories)"
echo ""
